id: gcp_keyvaluestore
namespace: prod

inputs:
  - id: is_prod
    type: BOOLEAN
    displayName: Running in production?
    defaults: false

tasks:
  - id: if_dev
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.is_prod == false }}"
    then:
    - id: gcp_dev_project_id
      type: io.kestra.plugin.core.kv.Set
      key: GCP_PROJECT_ID
      kvType: STRING
      value: zurich-air-quality
    - id: gcp_dev_location
      type: io.kestra.plugin.core.kv.Set
      key: GCP_LOCATION
      kvType: STRING
      value: europe-west6
    - id: gcp_dev_bucket_name
      type: io.kestra.plugin.core.kv.Set
      key: GCP_BUCKET_NAME
      kvType: STRING
      value: zaq_data_files_dev
    - id: gcp_dev_dataset
      type: io.kestra.plugin.core.kv.Set
      key: GCP_DATASET
      kvType: STRING
      value: air_quality_data_dev

  - id: if_prod
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.is_prod == true }}"
    then:
    - id: gcp_project_id
      type: io.kestra.plugin.core.kv.Set
      key: GCP_PROJECT_ID
      kvType: STRING
      value: zurich-air-quality
    - id: gcp_location
      type: io.kestra.plugin.core.kv.Set
      key: GCP_LOCATION
      kvType: STRING
      value: europe-west6
    - id: gcp_bucket_name
      type: io.kestra.plugin.core.kv.Set
      key: GCP_BUCKET_NAME
      kvType: STRING
      value: zaq_data_files
    - id: gcp_dataset
      type: io.kestra.plugin.core.kv.Set
      key: GCP_DATASET
      kvType: STRING
      value: air_quality_data